### ISSUE TITLE
[QUESTION] Is there an easy way to debug panels? (e.g., change colors to figure out how much space each panel takes up)

### ISSUE THREAD

**Issue by boop-the-dog** [CottonMC/LibGui#131]
Is there an easy way to figure out how much space a panel takes up? I've tried to play around with the BackgroundPainter and can't get it to change the colour.

Thanks in advance!

**Comment by Juuxel** [comment]
There are some things you can do instead of a `BackgroundPainter`:

- Use your IDE's debugger to look at the sizes of panels and other widgets
- If you're developing LibGui itself (probably not, but still 😄), you can modify `WPanel` directly
- You can make temporary mixins to `WPanel` to modify the painting code

Also note that you have to override `GuiDescription.addPainters` if you want to change the root panel's painter.

**Comment by boop-the-dog** [comment]
Thanks, in addition, does the BackgroundPainter take an RGBA input or just RGB? I can get panel's backgrounds to disappear but can't get them to be other colors than the default or transparent
