### ISSUE TITLE
[Question] How does WButton send C2SPacket? Or is it used in the wrong way?

### ISSUE THREAD

**Issue by q962** [CottonMC/LibGui#135]
```java
ScreenHandlerRegistry.registerSimple(MOUSE_ID,
                (syncId, inventory) -> new MouseBlockCraftingGuiDescription(syncId, inventory, ScreenHandlerContext.EMPTY));
```
- `WButton.setOnClick` is only executed on the client.
  - Because of `ScreenHandlerContext.EMPTY`, `ScreenHandlerContext.run` will not be executed
  - So that my operations will not be synchronized
- `SyncedGuiDescription.onSlotClick` is executed on the client and server.

![image](https://user-images.githubusercontent.com/15686075/130312006-5ae09393-dc9f-419b-bbb4-bdd411a88881.png)

**Comment by Juuxel** [comment]
It doesn't send any packets by default (click listeners are only run on the client), but you can use [`ScreenNetworking`](https://cottonmc.github.io/docs/libgui/io/github/cottonmc/cotton/gui/networking/ScreenNetworking.html) or your own custom packets to sync button presses. Slots are a bit of a special case because vanilla syncs them itself (they aren't really widgets in the same sense since they just wrap vanilla stuff).

**Comment by q962** [comment]
Problem solving
