### ISSUE TITLE
If I open my gui, the game crashes.

### ISSUE THREAD

**Issue by ckclol** [CottonMC/LibGui#141]
**Rendering bug**

**To Reproduce**
I used template code
```java
package tcfplayz.chemicals.screens;

import io.github.cottonmc.cotton.gui.client.LightweightGuiDescription;
import io.github.cottonmc.cotton.gui.widget.WButton;
import io.github.cottonmc.cotton.gui.widget.WGridPanel;
import io.github.cottonmc.cotton.gui.widget.WLabel;
import io.github.cottonmc.cotton.gui.widget.WSprite;
import io.github.cottonmc.cotton.gui.widget.data.Insets;
import net.minecraft.text.LiteralText;
import net.minecraft.util.Identifier;

public class ChemicalTableGui extends LightweightGuiDescription {
    public ChemicalTableGui() {
        WGridPanel root = new WGridPanel();
        setRootPanel(root);
        root.setSize(256, 240);
        root.setInsets(Insets.ROOT_PANEL);

        WSprite icon = new WSprite(new Identifier("minecraft:textures/item/redstone.png"));
        root.add(icon, 0, 2, 1, 1);

        WButton button = new WButton(new LiteralText("e"));
        root.add(button, 0, 3, 4, 1);

        WLabel label = new WLabel(new LiteralText("Test"), 0xFFFFFF);
        root.add(label, 0, 4, 2, 1);

        root.validate(this);
    }
}
```
and this in my block class
```java
@Override
    public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, Hand hand, BlockHitResult hit) {
        if (!world.isClient) {
            MinecraftClient.getInstance().setScreen(new CottonClientScreen(new ChemicalTableGui()));
        }
        return ActionResult.SUCCESS;
    }
```

**Expected behavior**
Gui opens.

**Version:**
 - LibGui 4.2.1+1.17.1
 - Fabric API 0.41.3+1.17
 - Minecraft 1.17.1

**Logs**
https://pastebin.com/bAXtpRrF

Related to https://github.com/CottonMC/LibGui/issues/124 but it didn't help.

**Comment by Juuxel** [comment]
You can't call `MinecraftClient.openScreen` (or any other `MinecraftClient` methods for that matter) from `Block.onUse` or `Item.use`. That leads to the game crashing either because of threading issues or because you can't use client-only classes on a dedi server. (In this case, the threading issues most likely - I can't access your pastebin to check.)

To fix this, you can either
- use a [`SyncedGuiDescription`](https://github.com/CottonMC/LibGui/wiki/Getting-Started-with-GUIs) or
- send a custom screen opening packet and call `setScreen` on the main client thread from the handler (the Fabric wiki has instructions on networking code).

**Comment by ckclol** [comment]
thanks, will try when I go home

**Comment by ckclol** [comment]
works

**Comment by jsaperr** [comment]
i cant seem to figure out how to use the synced gui description. could you send an example of it in your code if at all possible?
