### ISSUE TITLE
Game crashes when trying to open Gui and/or creative menue

### ISSUE THREAD

**Issue by ButterKing-28** [CottonMC/LibGui#201]
**Describe the bug**
When I go into the game it crashes when it right-click on the Gui item.

**To Reproduce**
1. Install the 1.20 version 8.0.0
2. update your mod from 1.19.3 to 1.20.1
3. load the game and right-click a GUI item

**Expected behavior** 
Here is the error output:
      Caused by: java.lang.UnsupportedOperationException: [LibGui] Screens cannot be opened in item use methods. Some alternatives 
       include:

      Process 'command 'C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin\java.exe'' finished with non-zero exit value -1

**Version of the (please complete the following information):**
 - Mod - 8.0.0 for 1.20
 - fabric_version=0.83.0+1.20.1
 - Minecraft - 1.20.1

**Comment by Juuxel** [comment]
This is not a bug - the way you are trying to open a screen from an item is broken and can easily crash with threading or environment issues.

Read the error message to see how you can fix the crash, it has a list of suggestions.

**Comment by hugh19se** [comment]
I also ran in to this error. I got it when I was following the video guide in your wiki:
https://github.com/CottonMC/LibGui/wiki/Client-Sided-Guis

The error message you are referring to lists no alternatives:
`Caused by: java.lang.UnsupportedOperationException: [LibGui] Screens cannot be opened in item use methods. Some alternatives include:
`

In the written version of the guide, it does show how to open the menu, but it doesn't explain where it is appropriate to do so.
